apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  # User DB
  POSTGRES_DB: "user_service_test"
  # Db user
  POSTGRES_USER: "postgres"
  # Db password
  POSTGRES_PASSWORD: "$2a$10$1rhrSG/QRr/Vk5h0ALQGRe.uLYkEE0FCtlOsd7/TaM.2M82txtdXW"
  DB_POD_NAME: "postgresdb"